### ISSUE TITLE
What is CURL_1P3A

### ISSUE THREAD

**Issue by blainehill2001** [xjasonlyu/1point3acres#4]
After digging into your code, I am unsure of where you obtain CURL_1P3A env var from.

I know there is an api.1point3acre[s].com, but without any documentation it seems unhelpful on how to decipher the proper headers to use.

**Comment by xjasonlyu** [comment]
It requires some MITM techniques to extract the `CURL_1P3A` data from the app. :-P

**Comment by blainehill2001** [comment]
I see. I've followed others' suggestions to get the cookies once you [login and view the network requests](https://raw.githubusercontent.com/harryhare/1point3acres/6a51c4a374c26fba9303b85ac951e4b358cc0ae6/screenshots/cookie.png)

Do we simply need to recreate this get request using curl?

**Comment by xjasonlyu** [comment]
it's not the same. It should be acquired in the app not the web.

**Comment by blainehill2001** [comment]
There is a curl request sent by the app labeled "CURL_1P3A" that we have to intercept and copy? 

I haven't ever used the app so I will need to dig into that.

**Comment by xjasonlyu** [comment]
Oops, I just checked. This script no longer works because 1ponit3acres has updated its check-in module.

**Comment by blainehill2001** [comment]
Gotcha haha. If you update this repo I will be excited!!
